version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: fetchwork-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./server
    container_name: fetchwork-backend
    restart: unless-stopped
    environment:
      PORT: 10000
      MONGO_URI: mongodb://admin:${MONGO_ROOT_PASSWORD}@mongodb:27017/fetchwork?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb
    ports:
      - "10000:10000"

  frontend:
    build: ./client
    container_name: fetchwork-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongodb_data:
